name: MySQL to SQLite3 Converter
description: Connect to mysql and convert to sqlite3 file
author: "ben.rowe.83@gmail.com"

inputs:
  output:
    description: output file
    required: true
  database:
    description: mysql database name
    required: true
  host:
    description: mysql host address
    required: true
  username:
    description: mysql username
    required: true
  port:
    description: mysql port
    required: true
  password:
    description: mysql password
    required: true

outputs:
  file:
    description: The file that is generated

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.database }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.output }}

branding:
  icon: "filter"
  color: "blue"

