name: Dockerhub Deploy

on:
  push:
    branches:
      - feature/*


jobs:
  test:
    name: Test conversion utility
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_USER: user
          MYSQL_DATABASE: example
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install DB Into MySQL
        env:
          PORT: ${{ job.services.mysql.ports['3306'] }}
        run: mysql --host 127.0.0.1 --port 32574 -uuser -ppassword example < example.sql
      - name: Convert MySQL to SQLite
        uses: ./
        with:
          host: 127.0.0.1
          port: 32574
          username: user
          password: password
          database: example
          output: tmp.sqlite
      - name: Verify conversion
        run: echo "todo"

